#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TARGET_REPO=""
MODEL=""
PROFILE="write-safe"
OLLAMA_BASE_URL="http://127.0.0.1:11434"
NO_PULL=false
DRY_RUN=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    --target-repo|-TargetRepo)
      TARGET_REPO="$2"
      shift 2
      ;;
    --model|-Model)
      MODEL="$2"
      shift 2
      ;;
    --profile|-Profile)
      PROFILE="$2"
      shift 2
      ;;
    --ollama-base-url|-OllamaBaseUrl)
      OLLAMA_BASE_URL="$2"
      shift 2
      ;;
    --no-pull|-NoPull)
      NO_PULL=true
      shift
      ;;
    --dry-run|-DryRun)
      DRY_RUN=true
      shift
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      exit 1
      ;;
  esac
done

if [ -z "$TARGET_REPO" ]; then
  printf 'Target repository is required. Use --target-repo <path>.\n' >&2
  exit 1
fi

if [ -z "$MODEL" ]; then
  printf 'Model is required. Use --model <name>.\n' >&2
  exit 1
fi

case "$PROFILE" in
  write-safe) PROFILE_LABEL="1 - WRITE SAFE" ;;
  plan-only) PROFILE_LABEL="2 - PLAN ONLY" ;;
  deep-review) PROFILE_LABEL="3 - DEEP REVIEW" ;;
  *)
    printf 'Unsupported profile: %s\n' "$PROFILE" >&2
    exit 1
    ;;
esac

BASE_CONFIG="$TARGET_REPO/.continue/config.yaml"
LOCAL_CONFIG="$TARGET_REPO/.continue/config.local.yaml"

if [ ! -f "$BASE_CONFIG" ]; then
  printf 'Target repository must already have .continue/config.yaml. Install the pack first.\n' >&2
  exit 1
fi

if [ "$DRY_RUN" = true ]; then
  printf "Would install validated model '%s' for profile '%s'.\n" "$MODEL" "$PROFILE_LABEL"
  if [ "$NO_PULL" = false ]; then
    printf 'Would pull model from configured Ollama endpoint.\n'
  fi
  printf 'Would write local-only config: %s\n' "$LOCAL_CONFIG"
  exit 0
fi

if [ "$NO_PULL" = false ]; then
  if ! command -v curl >/dev/null 2>&1; then
    printf 'curl is required unless --no-pull is used.\n' >&2
    exit 1
  fi
  OLLAMA_BASE_URL="${OLLAMA_BASE_URL%/}"
  printf 'Pulling %s\n' "$MODEL"
  curl -fsS "$OLLAMA_BASE_URL/api/pull" \
    -H "Content-Type: application/json" \
    -d "{\"model\":\"$MODEL\",\"stream\":false}" >/dev/null
  printf 'Pulled %s\n' "$MODEL"
fi

SOURCE_CONFIG="$BASE_CONFIG"
if [ -f "$LOCAL_CONFIG" ]; then
  SOURCE_CONFIG="$LOCAL_CONFIG"
fi

PYTHON_COMMAND=""
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1; then
    PYTHON_COMMAND="$candidate"
    break
  fi
done

if [ -z "$PYTHON_COMMAND" ]; then
  printf 'python3 or python is required to update the local model config.\n' >&2
  exit 1
fi

IFS=$'\t' read -r RUNTIME_RESIDENCY_MODE MAX_RESIDENT_MODELS PRELOAD_KEEP_ALIVE_MINUTES <<< "$("$SCRIPT_DIR/get-model-runtime-policy.shared.sh")"
CONTINUE_KEEP_ALIVE_SECONDS=$((PRELOAD_KEEP_ALIVE_MINUTES * 60))
if [ "$RUNTIME_RESIDENCY_MODE" = "unload-after-run" ]; then CONTINUE_KEEP_ALIVE_SECONDS=0; fi

"$PYTHON_COMMAND" - "$SOURCE_CONFIG" "$LOCAL_CONFIG" "$PROFILE" "$MODEL" "$CONTINUE_KEEP_ALIVE_SECONDS" <<'PY'
from pathlib import Path
import sys

source = Path(sys.argv[1])
target = Path(sys.argv[2])
profile = sys.argv[3]
selected_model = sys.argv[4].strip()
continue_keep_alive_seconds = int(sys.argv[5])

profiles = [
    ("write-safe", "1 - WRITE SAFE", ["chat", "edit", "apply"]),
    ("plan-only", "2 - PLAN ONLY", ["chat"]),
    ("deep-review", "3 - DEEP REVIEW", ["chat"]),
]

replacement = ["models:"]
for profile_id, label, roles in profiles:
    model = selected_model if profile_id == profile else "qwen3.5:9b"
    replacement.extend([
        f"  - name: {label} - {model}",
        "    provider: ollama",
        f"    model: {model}",
        "    roles:",
    ])
    replacement.extend([f"      - {role}" for role in roles])
    replacement.extend([
        "    capabilities:",
        "      - tool_use",
        "    defaultCompletionOptions:",
        "      temperature: 0.2",
        "      contextLength: 16384",
        "      maxTokens: 2048",
        f"      keepAlive: {continue_keep_alive_seconds}",
    ])

replacement.extend([
    "  - name: Ollama Nomic Embed",
    "    provider: ollama",
    "    model: nomic-embed-text",
    "    roles:",
    "      - embed",
])

lines = source.read_text().splitlines()
updated = []
skip = False
inserted = False
for line in lines:
    if line.strip() == "models:" and not line.startswith((" ", "\t")):
        updated.extend(replacement)
        skip = True
        inserted = True
        continue
    if skip and line and not line.startswith((" ", "\t")) and line.split(":", 1)[0].replace("-", "").replace("_", "").isalnum():
        skip = False
    if not skip:
        updated.append(line)

if not inserted:
    raise SystemExit("Could not find top-level models section in config.")

header = [
    "# Local-only Continue config generated by install-validated-model.shared.sh.",
    "# Do not commit this file. It may contain machine-specific model choices.",
]
target.write_text("\n".join(header + updated) + "\n")
PY

printf 'Updated local Continue config: %s\n' "$LOCAL_CONFIG"
printf 'Profile: %s\n' "$PROFILE_LABEL"
printf 'Model: %s\n' "$MODEL"
