#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCE_CONTINUE="$REPO_ROOT/.continue"
TARGET_REPO=""
DRY_RUN=false
AUTO_MODEL_CONFIG=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    --target-repo|-TargetRepo)
      TARGET_REPO="$2"
      shift 2
      ;;
    --dry-run|-DryRun)
      DRY_RUN=true
      shift
      ;;
    --auto-model-config|-AutoModelConfig)
      AUTO_MODEL_CONFIG=true
      shift
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      exit 1
      ;;
  esac
done

if [ -z "$TARGET_REPO" ]; then
  printf 'Target repository is required. Use --target-repo <path>.\n' >&2
  exit 1
fi

if [ ! -d "$SOURCE_CONTINUE" ]; then
  printf 'Source .continue folder does not exist: %s\n' "$SOURCE_CONTINUE" >&2
  exit 1
fi

if [ ! -d "$TARGET_REPO" ]; then
  printf 'Target repository path does not exist: %s\n' "$TARGET_REPO" >&2
  exit 1
fi

REPO_ROOT_RESOLVED="$(cd "$REPO_ROOT" && pwd)"
TARGET_RESOLVED="$(cd "$TARGET_REPO" && pwd)"

if [ "$REPO_ROOT_RESOLVED" = "$TARGET_RESOLVED" ]; then
  printf 'Target repository must be different from this pack repository.\n' >&2
  exit 1
fi

TARGET_CONTINUE="$TARGET_RESOLVED/.continue"
BACKUP_CONTINUE="$TARGET_RESOLVED/.continue.backup-$(date '+%Y%m%d-%H%M%S')"

printf 'Installing Continue pack into %s\n' "$TARGET_RESOLVED"

if [ "$DRY_RUN" = true ]; then
  printf 'Dry run only. No files will be changed.\n'
  if [ -d "$TARGET_CONTINUE" ]; then
    printf 'Would back up existing .continue to %s\n' "$BACKUP_CONTINUE"
  fi
  printf 'Would copy .continue files excluding config.local*.yaml.\n'
  if [ "$AUTO_MODEL_CONFIG" = true ]; then
    printf 'Would generate .continue/config.local.yaml using the hardware profile recommended model.\n'
  fi
  exit 0
fi

if [ -d "$TARGET_CONTINUE" ]; then
  mv "$TARGET_CONTINUE" "$BACKUP_CONTINUE"
  printf 'Backed up existing .continue to %s\n' "$BACKUP_CONTINUE"
fi

mkdir -p "$TARGET_CONTINUE"

while IFS= read -r source_file; do
  relative="${source_file#$SOURCE_CONTINUE/}"
  case "$relative" in
    config.local*.yaml|config.local*.yml) continue ;;
  esac

  destination="$TARGET_CONTINUE/$relative"
  mkdir -p "$(dirname "$destination")"
  cp "$source_file" "$destination"
done < <(find "$SOURCE_CONTINUE" -type f)

if [ ! -f "$TARGET_CONTINUE/config.yaml" ]; then
  printf 'Installed config is missing: %s\n' "$TARGET_CONTINUE/config.yaml" >&2
  exit 1
fi

CONFIG_CONTENT="$(cat "$TARGET_CONTINUE/config.yaml")"
FILE_REFS="$(printf '%s\n' "$CONFIG_CONTENT" | grep -Eo 'file://\./[^[:space:]]+' | sed 's#file://./##' || true)"

while IFS= read -r ref; do
  [ -z "$ref" ] && continue
  if [ ! -e "$TARGET_CONTINUE/$ref" ]; then
    printf 'Installed file reference does not resolve: %s\n' "$ref" >&2
    exit 1
  fi
done <<EOF
$FILE_REFS
EOF

if [ "$AUTO_MODEL_CONFIG" = true ]; then
  case "$(uname -s 2>/dev/null || true)" in
    Darwin*) profile_script="$REPO_ROOT/scripts/get-local-model-profile.macos.sh" ;;
    *) profile_script="$REPO_ROOT/scripts/get-local-model-profile.linux.sh" ;;
  esac

  if [ ! -x "$profile_script" ]; then
    printf 'Hardware profile script is missing or not executable: %s\n' "$profile_script" >&2
    exit 1
  fi

  profile_json="$("$profile_script" --json)"
  recommended_model="$(printf '%s\n' "$profile_json" | sed -n 's/.*"PrimaryModel":"\([^"]*\)".*/\1/p' | head -n 1)"

  if [ -z "$recommended_model" ]; then
    printf 'Hardware profile did not return a recommended model.\n' >&2
    exit 1
  fi

  {
    printf '# Local-only Continue config generated by install-continue-pack.shared.sh.\n'
    printf '# Do not commit this file. It may contain machine-specific model choices.\n'
    awk -v model="$recommended_model" '
      BEGIN { replaced = 0 }
      /^[[:space:]]*model:[[:space:]]*/ && replaced == 0 {
        sub(/model:.*/, "model: " model)
        replaced = 1
      }
      { print }
    ' "$TARGET_CONTINUE/config.yaml"
  } > "$TARGET_CONTINUE/config.local.yaml"

  printf 'Generated local model config: %s\n' "$TARGET_CONTINUE/config.local.yaml"
  printf 'Selected model: %s\n' "$recommended_model"
fi

printf 'Install complete.\n'
